name: Merge main into main-v3

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  merge-pr-to-main-v3:
    name: Merge the PR into main-v3
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to access previous commits

      - name: Set up Git User Information
        run: |
          # Check if the event is a pull request and set user info accordingly
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            USER_NAME="${{ github.event.pull_request.user.login }}"
            USER_EMAIL="${{ github.event.pull_request.user.email }}"
          else
            USER_NAME="${{ github.actor }}"
            USER_EMAIL="${{ github.actor }}@users.noreply.github.com"  # Default email format for direct commits
          fi
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"


      - name: Identify the PR number
        id: pr-info
        run: |
          # Use the PR number directly from the event if available
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          else
            # Extract PR number from the merge commit title if it's a push event
            PR_NUMBER=$(git log -1 --pretty=%B | grep -oE '#[0-9]+' || echo "")
            PR_NUMBER=${PR_NUMBER#"#"}  # Remove '#' character
          fi
          echo "PR_NUMBER: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: List, Count, and Check Open PRs to main-v3
        id: list-count-check-prs
        run: |
          # Fetch all open PR numbers targeting main-v3 from main
          OPEN_PRS=$(gh pr list --base main-v3 --state open --json number --jq '.[].number')

          # Log the raw OPEN_PRS output for debugging purposes
          echo "RAW OPEN_PRS: $OPEN_PRS"

          # Check if OPEN_PRS is empty or null and handle appropriately
          if [[ "$OPEN_PRS" == "[]" || -z "$OPEN_PRS" ]]; then
            echo "No open PRs targeting main-v3."
            # Set OPEN_PRS_FOR_MAIN_V3 to an empty string
            echo "OPEN_PRS_FOR_MAIN_V3=" >> $GITHUB_ENV
            echo "MULTIPLE_OPEN_PRS=false" >> $GITHUB_ENV
          else
            # Convert the space-separated list into an array, sort it, and join it with commas
            OPEN_PRS_COMMA_SEPARATED=$(echo "$OPEN_PRS" | tr ' ' '\n' | sort -n | tr '\n' ',' | sed 's/,$//')

            # Log the formatted OPEN_PRS_COMMA_SEPARATED for debugging purposes
            echo "OPEN_PRS_COMMA_SEPARATED: $OPEN_PRS_COMMA_SEPARATED"
          
            # Set OPEN_PRS_FOR_MAIN_V3 to the properly formatted string
            echo "OPEN_PRS_FOR_MAIN_V3=$OPEN_PRS_COMMA_SEPARATED" >> $GITHUB_ENV
          
            # Check if there are multiple open PRs
            OPEN_PR_COUNT=$(echo "$OPEN_PRS_COMMA_SEPARATED" | tr ',' '\n' | wc -l)
            if [[ "$OPEN_PR_COUNT" -gt 1 ]]; then
              echo "Multiple open PRs found, setting flag to true."
              echo "MULTIPLE_OPEN_PRS=true" >> $GITHUB_ENV
            else
              echo "Only one or no open PRs found."
              echo "MULTIPLE_OPEN_PRS=false" >> $GITHUB_ENV
            fi
          fi

          # Log the final outputs for verification
          echo "FINAL OUTPUTS:"
          echo "OPEN_PRS_FOR_MAIN_V3=${{ env.OPEN_PRS_FOR_MAIN_V3 }}"
          echo "MULTIPLE_OPEN_PRS=${{ env.MULTIPLE_OPEN_PRS }}"


      - name: Create a new branch for merge
        id: create-branch
        run: |
          # Max branch name length allowed by Git is 255 characters.
          MAX_LENGTH=255

          # Fetch the author's name, sanitize, and trim it to a readable length
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an' | sed 's/ /-/g' | cut -c1-20) # Trim to 20 chars for readability

          # Get short commit hash (7 characters for brevity)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

          # Check if there's a PR number to generate branch name
          if [ -n "${{ env.PR_NUMBER }}" ]; then
            MERGE_BRANCH_NAME="merge/main-v3/${AUTHOR_NAME}/pr-${{ env.PR_NUMBER }}"
          else
            TIMESTAMP=$(date +'%Y%m%d-%H%M')
            MERGE_BRANCH_NAME="merge/main-v3/${AUTHOR_NAME}/${COMMIT_HASH}-${TIMESTAMP}"
          fi

          # Ensure branch name does not exceed 255 characters
          MERGE_BRANCH_NAME=$(echo "$MERGE_BRANCH_NAME" | cut -c1-$MAX_LENGTH)

          # Delete existing branch if it already exists
          if git ls-remote --exit-code --heads origin "$MERGE_BRANCH_NAME"; then
            echo "Branch $MERGE_BRANCH_NAME already exists. Deleting the branch to start fresh."
            git push origin --delete "$MERGE_BRANCH_NAME"
          fi
          
          # Create and push the new branch
          git checkout -b "$MERGE_BRANCH_NAME"
          git push origin "$MERGE_BRANCH_NAME"
          echo "MERGE_BRANCH_NAME=$MERGE_BRANCH_NAME" >> $GITHUB_ENV


      - name: Handle PR creation or clean merge
        run: |
          # Fetch the latest changes from both main and main-v3 branches
          git fetch origin main-v3
          
          # Checkout the main-v3 branch
          git checkout main-v3
          
          # Attempt to merge main into main-v3
          if git merge "${{ env.MERGE_BRANCH_NAME }}" --no-commit --no-ff; then
            # Check the status of the merge to see if there are changes to commit
            if [[ "$(git diff --stat --cached)" != "" && "${{ env.MULTIPLE_OPEN_PRS }}" == "false" ]]; then
              echo "⏩ Changes detected, proceeding with direct merge."
              git commit -m "Merging changes [${{ env.COMMIT_HASH }}] from ${{ env.MERGE_BRANCH_NAME }} to main-v3"
              git push origin main-v3
              echo "✅ Successfully merged to main-v3"
            else
              echo "ℹ️ No changes to merge; nothing to commit."
            fi
            # Delete the temporary branch after successful merge or no changes
            git push origin --delete "${{ env.MERGE_BRANCH_NAME }}"
            echo "🧹 Temporary branch ${{ env.MERGE_BRANCH_NAME }} deleted successfully."
          else
            # If there are merge conflicts, notify and create a PR for manual resolution
            echo "🚫 Merge conflicts detected, creating PR for manual resolution."
            MERGE_BRANCH_URL="https://github.com/${{ github.repository }}/tree/${{ env.MERGE_BRANCH_NAME }}"
          
            # Construct the PR description based on whether there are multiple open PRs
            if [[ "${{ env.MULTIPLE_OPEN_PRS }}" == "true" ]]; then
              # Replace commas with ", #" and prepend "#" to each PR number
              PR_DESCRIPTION="Depends on the PRs: $(echo "${{ env.OPEN_PRS_FOR_MAIN_V3 }}" | sed 's/,/, #/g' | sed 's/^/#/')"
            else
              PR_DESCRIPTION=""
            fi
          
            # Set the draft flag based on MULTIPLE_OPEN_PRS
            DRAFT_FLAG=$([[ "${{ env.MULTIPLE_OPEN_PRS }}" == "true" ]] && echo "--draft" || echo "")
            echo "DRAFT_FLAG: $DRAFT_FLAG"
          
            # Create a pull request for the merge conflicts
          
            # Ensure the variables are properly sanitized for use in the command
            echo "MERGE_BRANCH_URL: $MERGE_BRANCH_URL"
            echo "PR_DESCRIPTION: $PR_DESCRIPTION"
            MERGE_BRANCH_URL_SAFE=$(echo "$MERGE_BRANCH_URL" | sed 's/"/\\"/g')   # Escape double quotes
            PR_DESCRIPTION_SAFE=$(echo "$PR_DESCRIPTION" | sed 's/"/\\"/g')       # Escape double quotes
          
            echo "MERGE_BRANCH_URL_SAFE: $MERGE_BRANCH_URL_SAFE"
            echo "PR_DESCRIPTION_SAFE: $PR_DESCRIPTION_SAFE"
          
            gh pr create $DRAFT_FLAG \
              --base main-v3 \
              --head "${{ env.MERGE_BRANCH_NAME }}" \
              --title "Resolve conflicts while merging ${{ env.MERGE_BRANCH_NAME }} into main_v3" \
              --body "Merge conflicts occurred while attempting to merge changes ${{ env.COMMIT_HASH }} from $MERGE_BRANCH_URL_SAFE to main-v3. Please resolve the conflicts. $PR_DESCRIPTION_SAFE"
          
            echo "✅ Pull request created for manual resolution."
          fi


      - name: Merge resolution instruction
        if: failure()
        run: |
          echo "⛙ Merge conflicts must be resolved manually. PR created for branch ${{ env.MERGE_BRANCH_NAME }}."
